### ISSUE TITLE
ex-04-3

### ISSUE THREAD

**Issue by Julia-uerj** [Julia-uerj/LP1#4]
@fsantanna, tentei refazer como você mostrou em sala. 

Ainda não consegui resolver. 

Preciso passar o apontador para o vetor, como argumento para a função ``preenche_vetor()`` . Correto?

Da maneira que você mostrou... 

``
    preenche_vetor(struct Ponto* vet, 10);
``

ou

``
    preenche_vetor(struct Ponto vet[], 10);
``

O que mais está incorreto? Não consigo entender a mensagem de erro de compilação...

https://github.com/Julia-uerj/LP1/blob/master/vetores/ex-04-3.c

**Comment by fsantanna** [comment]
Não estou vendo o código inteiro, mas você quer passar um vetor que já está declarado, então não tem esse `struct Ponto` na passagem:

`preenche_vetor(vet, 10)`

**Comment by fsantanna** [comment]
Do mesmo modo que você não diz o tipo de 10 ao passá-lo...

Isso não faz sentido:

`preenche_vetor(struct Ponto vet[], int 10);`

O correto é:

`preenche_vetor(vet, 10);`

Sem os tipos.

**Comment by Julia-uerj** [comment]
Isso... Testei rapidamente aqui, mas apareceram outros erros... Já atualizo.

Em 13 de jun de 2018 10:47 AM, fsantanna <notifications@github.com> escreveu:

Do mesmo modo que você não diz o tipo de 10 ao passá-lo...

Isso não faz sentido:

preenche_vetor(struct Ponto vet[], int 10);

O correto é:

preenche_vetor(vet, 10);

Sem os tipos.
